/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.pizzabot

import de.pizzabot.display.StreamDisplay
import de.pizzabot.input.StreamInput
import de.pizzabot.robot.PizzaOrderRobot
import de.pizzabot.robot.StandardPrices

class App {
    companion object {
        fun run() {
            val display = StreamDisplay(System.out)
            val input = StreamInput(display, System.`in`)
            val robot = PizzaOrderRobot(display, input, StandardPrices)

            robot.displayMenu()
            robot.collectOrders().first().also {
                robot.bakePizza(it)
                robot.displayBill(it)
            }

        }
    }
}

fun main() {
    App.run()
}
