/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.springboot;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;

import org.example.springboot.services.UserInterface;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        ApplicationContext app = SpringApplication.run(App.class, args);
        UserInterface ui = app.getBean(UserInterface.class);
        ui.showGreeting("user");
    }
}
