/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.spring;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {
    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
        context.scan("org.example.spring");
        context.refresh();

        UserInterface ui = context.getBean(UserInterface.class);

        ui.showGreeting();
    }
}
