/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.springbootconfig;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        ApplicationContext app = SpringApplication.run(App.class, args);
    }
}
